public with sharing class futureMethodDemo {
    public futureMethodDemo() {
        method1();
        method2();
        method3(); 
        method4();
        method5();
        method6();
        method7();
        method8();
        method9();
        method10();
        method11();
        method12();
        method13();
        method14();
        method15();
        method16();
        method17();
        method18();
        method19();
        method20();
        method21();
        method22();
        method23();
        method24();
        method25();
        method26();
        method27();
        method28();
        method29();
        method30();
        method31();
        method32();
        method33();
        method34();
        method35();
        method36();
        method37();
        method38();
        method39();
        method40();
        method41();
        method42();
        method43();
        method44();
        method45();
        method46();
        method47();
        method48();
        method49();
        method50();
        method51();
    }

    public static void method1() {
        System.debug('inside method 1');
    }
    
    @future(callout=true)
    public static void method2(){
        system.debug('inside non static method 2');
    }

    public static void method3(){
        System.debug('inside method 3');
    }

   

    @future(callout=true)
    public static void method4(){
        system.debug('inside static method 4');
    }
    
    public static void method5(){
        System.debug('inside method 5');
    }

    @future(callout=true)
    public static void method6(){
        system.debug('inside static method 6');
    }

    public static void method7(){
        System.debug('inside method 7');
    }


    @future(callout=true)
    public static void method8(){
        system.debug('inside static method 8');
    }



    @future(callout=true)
    public static void method9(){
        system.debug('inside method 9');
    }

    public static void method10(){
        System.debug('inside method 10');
    }

    public static void method11(){
        System.debug('inside method 11');
    }

    @future(callout=true)
    public static void method12(){
        system.debug('inside method 12');
    }

    @future(callout=true)
    public static void method13(){
        system.debug('inside method 13');
    }

    @future(callout=true)
    public static void method14(){
        system.debug('inside method 14');
    }

    @future(callout=true)
    public static void method15(){
        system.debug('inside method 15');}


    @future(callout=true)
    public static void method16(){
        system.debug('inside method 16');}

    @future(callout=true)
    public static void method17(){
        system.debug('inside method 17');}

        @future(callout=true)
    public static void method18(){
        system.debug('inside method 18');}

        @future(callout=true)
    public static void method19(){
        system.debug('inside method 19');}


        @future(callout=true)
    public static void method20(){
        system.debug('inside method 20');}


        @future(callout=true)
    public static void method21(){
        system.debug('inside method 21');}




        @future(callout=true)
    public static void method22(){
        system.debug('inside method 22');}

        @future(callout=true)
    public static void method23(){
        system.debug('inside method 23');}

        @future(callout=true)
    public static void method24(){
        system.debug('inside method 24');}

        @future(callout=true)
    public static void method25(){
        system.debug('inside method 25');}

        @future(callout=true)
    public static void method26(){
        system.debug('inside method 26');}

        @future(callout=true)
    public static void method27(){
        system.debug('inside method 27');}

        @future(callout=true)
    public static void method28(){
        system.debug('inside method 28');}

        @future(callout=true)
    public static void method29(){
        system.debug('inside method 29');}

        @future(callout=true)
    public static void method30(){
        system.debug('inside method 30');}


        @future(callout=true)
    public static void method31(){
        system.debug('inside method 31');}

        @future(callout=true)
    public static void method32(){
        system.debug('inside method 32');}

        @future(callout=true)
    public static void method33(){
        system.debug('inside method 33');}


        @future(callout=true)
    public static void method34(){
        system.debug('inside method 34');}

        @future(callout=true)
    public static void method35(){
        system.debug('inside method 35');}


        @future(callout=true)
    public static void method36(){
        system.debug('inside method 36');}

        @future(callout=true)
    public static void method37(){
        system.debug('inside method 37');}

        @future(callout=true)
    public static void method38(){
        system.debug('inside method 38');}

        @future(callout=true)
    public static void method39(){
        system.debug('inside method 39');}

        @future(callout=true)
    public static void method40(){
        system.debug('inside method 40');}

        @future(callout=true)
    public static void method41(){
        system.debug('inside method 41');}

        @future(callout=true)
    public static void method42(){
        system.debug('inside method 42');}

        @future(callout=true)
    public static void method43(){
        system.debug('inside method 43');}

        @future(callout=true)
    public static void method44(){
        system.debug('inside method 44');}

        @future(callout=true)
    public static void method45(){
        system.debug('inside method 45');}


        @future(callout=true)
    public static void method46(){
        system.debug('inside method 46');}

        @future(callout=true)
    public static void method47(){
        system.debug('inside method 47');}

        @future(callout=true)
    public static void method48(){
        system.debug('inside method 48');}

        @future(callout=true)
    public static void method49(){
        system.debug('inside method 49');}


        @future(callout=true)
    public static void method50(){
        system.debug('inside method 50');}

        @future(callout=true)
    public static void method51(){
        system.debug('inside method 51');}


}